on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/renv

permissions:
  contents: write
  pages: write

name: Render and deploy Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: update
        run: sudo apt-get update

      - name: Install curl
        run: sudo apt-get install -y libcurl4-openssl-dev libglpk-dev
      - name: Install git-lfs
        run: sudo apt-get install git-lfs

      - name: SetLocale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen es_ES.UTF-8
          sudo update-locale

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # uncomment and fill to pin a version
        # with:
        #   version: 0.9.105

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.3'

      - uses: r-lib/actions/setup-renv@v2
      - name: Install cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2, version = "2.34.0")
        shell: Rscript {0}


      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: notas/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
